### ISSUE TITLE
Potential dependency conflicts between brightside and amqp

### ISSUE THREAD

**Issue by NeolithEra** [BrighterCommand/Brightside#60]
Hi, as shown in the following full dependency graph of  **_brightside_**, **_brightside_** requires _**amqp**_ (the latest version)， while the installed version of **_kombu _**(4.6.8) requires _**amqp>=2.5.2,<2.6**_.

According to Pip's “first found wins” installation strategy, _**amqp 2.5.2**_ is the actually installed version.  

Although the first found package version _**amqp 2.5.2**_ just satisfies the later dependency constraint （_**amqp>=2.5.2,<2.6**_), it will lead to a build failure once developers release a newer version of amqp.

### Dependency tree--------
```
brightside  - 0.6.13
| +- amqp(install version:2.5.2 version range:*)
| +- eventlet(install version:0.25.2 version range:*)
| +- ez-setup(install version:0.9 version range:*)
| +- kombu(install version:4.6.8 version range:*)
| | +- amqp(install version:2.5.2 version range:>=2.5.2,<2.6)
| | +- importlib-metadata(install version:1.6.0 version range:>=0.18)
| +- poll(install version:1.0 version range:*)
| +- psycopg2(install version:2.8.5 version range:*)
| +- sqlalchemy(install version:1.3.16 version range:*)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Loosen the version range of **_amqp_** to be **_<=2.5.2_**.
2.	Remove your direct dependency **_amqp_**, and use the **_amqp_** transitively introduced by **_kombu _**.
3.	Ask your direct dependency kombu to loosen the version range of **_amqp_** to be **_>=2.5.2_**.
@iancooper Which solution do you prefer, 1 ,2 or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by iancooper** [comment]
@NeolithEra I would think we could opt for 2, as I believe we only use it through kombu (though if that trips us up, 1 seems better0.

A PR would be great
